### ISSUE TITLE
Update to newer version of magento2-rest-api

### ISSUE THREAD

**Issue by juho-jaakkola** [DivanteLtd/mage2vuestorefront#105]
The fix https://github.com/DivanteLtd/magento2-rest-client/commit/cb9b5c31e360f5aa0d2055ebd745458fcd0b1d5d is important for multistore setups, so please update the dependency from `0.0.2` to `0.0.12`

And then bump the version number in [package.json](https://github.com/DivanteLtd/mage2vuestorefront/blob/master/package.json#L4 ) from `1.11.0` to `1.11.1` so its's possible to upgrade projects to use the version with the updated dependency.

**Comment by juho-jaakkola** [comment]
> And then bump the version number in package.json...

Assuming `package.json` is the place where the current version is being read from. I am a bit confused where exactly the release tags are being maintained within this project/package.

**Comment by juho-jaakkola** [comment]
@pkarw Could this be assigned to someone?

Apologies for being pushy, but I'd need the version with the fix for a multistore go-live in the end of Septemper.

**Comment by gibkigonzo** [comment]
@juho-jaakkola Can you create pr, please? Also if you can update lodash https://github.com/DivanteLtd/mage2vuestorefront/pull/103 it would be awesome. I will then release 1.11.1

**Comment by juho-jaakkola** [comment]
@gibkigonzo I would upgrade `magento2-rest-client` but I do not understand how its releases are managed. It has the  version `0.0.12` mentioned [here](https://github.com/DivanteLtd/magento2-rest-client/blob/master/package.json#L64), but when I try to upgrade, that release is not available:

```
yarn upgrade magento2-rest-client@0.0.12
yarn upgrade v1.15.2
[1/4] 🔍  Resolving packages...
Couldn't find any versions for "magento2-rest-client" that matches "0.0.12"
? Please choose a version of "magento2-rest-client" from this list: (Use arrow keys)
❯ 0.0.2
  0.0.1
```

**Comment by gibkigonzo** [comment]
yes, I see that in vsf-api we use direct link to magento2-rest-client
`"magento2-rest-client": "github:DivanteLtd/magento2-rest-client",`
Please use same approach here @juho-jaakkola

**Comment by juho-jaakkola** [comment]
@gibkigonzo Ok, I got it now! Here is the PR: https://github.com/DivanteLtd/mage2vuestorefront/pull/106/files

I'm not sure what you meant be updating lodash. The link you provided takes to an existing PR, so what is there to do?

**Comment by gibkigonzo** [comment]
Yes, my mistake. Its merged

**Comment by juho-jaakkola** [comment]
For anyone running into this issue and needs a quick fix, VSF-API can be updated to use the new version by running:
```
yarn add -W git+https://github.com/DivanteLtd/mage2vuestorefront.git
```
