### ISSUE TITLE
Fix parallel import

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/mage2vuestorefront#11]
We need to test the products importer with --partitions=2 and more - it seems like a problem with queues is somewhere in there

**Comment by Cyclonecode** [comment]
I don't know if it is related, but I noticed that when running `node --harmony cli.js products --partitions=2` the following messages are displayed in the end:

```
2019-02-10T19:31:26.284Z - info: All pages processed!
2019-02-10T19:31:26.285Z - info: Task done!
```

But the process does not exit.

**Comment by Cyclonecode** [comment]
@pkarw - What kind of problems to you experience when running with multiple partitions?

**Comment by pkarw** [comment]
I haven't had any - it works for me :) There was this issue You had and which we discussed on Slack (when the partition number is zero due to too low number of records ?)

**Comment by Cyclonecode** [comment]
So you don't have any issues right now with that the process just hangs like mine does?

**Comment by pkarw** [comment]
Positive

**Comment by lukeromanowicz** [comment]
Closing due to op inactivity and lack of repro.
