### ISSUE TITLE
what URl do i add in MAGENTO_URL

### ISSUE THREAD

**Issue by ganeshr28** [DivanteLtd/mage2vuestorefront#12]
in src/config.js what URL do I need to add in below line
url:  process.env.MAGENTO_URL || 'http://magento2.demo-1.divante.pl/rest',

i am working on local my Magento 2 backend is on localhost/magento2/admin

need assistance i am confused

**Comment by pkarw** [comment]
You should probably have localhost/magento2/rest in there
