### ISSUE TITLE
Missing package.json

### ISSUE THREAD

**Issue by shkodasv** [DivanteLtd/mage2vuestorefront#19]
Hello!
Try to install mage2vuestorefront and got the error

`[valentina] (~/projects/divant-vs/mage2vs) (master)$ npm install
npm WARN saveError ENOENT: no such file or directory, open '/Users/valentina/projects/divant-vs/mage2vs/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/Users/valentina/projects/divant-vs/mage2vs/package.json'
npm WARN mage2vs No description
npm WARN mage2vs No repository field.
npm WARN mage2vs No README data
npm WARN mage2vs No license field.
`

There is no package.json, but it should be (seems) ?

Could you please help?

**Comment by pkarw** [comment]
Please just `cd src` and retry :)

**Comment by shkodasv** [comment]
thanks!
