### ISSUE TITLE
mage2nosql

### ISSUE THREAD

**Issue by zadigus** [DivanteLtd/mage2vuestorefront#23]
Hi,
What is the difference between mage2vuestorefront and mage2nosql?
Cheers

**Comment by pkarw** [comment]
The same project; renamed

**Comment by zadigus** [comment]
But because there are two repositories, how do I know which one is the latest? Which one should I work with? Thanks for the info!

**Comment by zadigus** [comment]
Well it seems like the project's git history says that mage2vuestorefront is the latest.
