### ISSUE TITLE
Magento images are not displaying in Vue-StoreFront

### ISSUE THREAD

**Issue by Anirudh0328** [DivanteLtd/mage2vuestorefront#29]
Hello,

I successfully connected Magento to Vue-StoreFront. I'm able to get all products in Vue-StoreFront which are added in Magento. **But I'm unable to get Magento product images in Vue-StoreFront.**

**How I will get my Magento product images in Vue-StoreFront??**

When I was installing Vue-StoreFront it was asked for image path , which path we need to provide there?either Magento image path or Vue-StoreFront path??
**I have imagemagic also, still it is not working.**
Anyone please help me.

Thanks in advance :),
Anirudh.

**Comment by zadigus** [comment]
Please have a look at this: https://github.com/DivanteLtd/mage2vuestorefront/issues/28 as I had the very same problem yesterday.

**Comment by Anirudh0328** [comment]
Hello,

Here I'm getting the images path in vue-storefront like

<img lazy="error" data-src="http://magento-sample-url/pub/media/catalog/product/310/300/resize/s/h/shirt_1.jpeg" alt="Ctel Shirts" src="/assets/placeholder.jpg" data-testid="productImage" data-v-af5f87e8="" height="300" width="310">

if I remove "310/300/resize" from the src URL I am able get the image in browser.

What is the issue?What I need to change?

**Comment by Darwex** [comment]
Hi.

I had the same issue, there was wrong url in generated config inside vue-storefront-api. I had to change value inside vue-storefront-api/config/local.json section magento2.imgUrl to "https://your.magento.host/pub/media/catalog/product".

**Comment by parnus01** [comment]
> Hello,
> 
> Here I'm getting the images path in vue-storefront like
> 
> `<img lazy="error" data-src="http://magento-sample-url/pub/media/catalog/product/310/300/resize/s/h/shirt_1.jpeg" alt="Ctel Shirts" src="/assets/placeholder.jpg" data-testid="productImage" data-v-af5f87e8="" height="300" width="310">`
> 
> if I remove "310/300/resize" from the src URL I am able get the image in browser.
> 
> What is the issue?What I need to change?

same problem do you have any idea for this ?

**Comment by pkarw** [comment]
You need to set magento2 img url (/pub/media/catalog ...) in the `vue-storefront-api/config/local.json`. Then in the `vue-storefront` You need to set `images.baseUrl` to point to `vue-storefront-api` which is usually: `localhost:8080/img`

**Comment by parnus01** [comment]
i change config in vue-storefront-api and run yarn dev to recomplie . but it got some error
`uncaughtException: listen EADDRINUSE 127.0.0.1:8080`

**Comment by Cyclonecode** [comment]
@parnus01 - The error message tells you that your `vue-storefront-api` instance is already running so you will need to terminate and restart the current node application.

**Comment by lukeromanowicz** [comment]
Closing due to OP inactivity.

**Comment by rahuljajra** [comment]
> Hello,
> 
> I successfully connected Magento to Vue-StoreFront. I'm able to get all products in Vue-StoreFront which are added in Magento. **But I'm unable to get Magento product images in Vue-StoreFront.**
> 
> **How I will get my Magento product images in Vue-StoreFront??**
> 
> When I was installing Vue-StoreFront it was asked for image path , which path we need to provide there?either Magento image path or Vue-StoreFront path??
> **I have imagemagic also, still it is not working.**
> Anyone please help me.
> 
> Thanks in advance :),
> Anirudh.

can you please advise how to Integrate Vue-storefront with local Magento.
 I have tried with all steps but not successfully integrated

**Comment by Anirudh0328** [comment]
Hello Rahul,



For that you have to install image magick(PHP-ImageMagick extension). One
try with that.

**Comment by rahuljajra** [comment]
> Hello Rahul, For that you have to install image magick(PHP-ImageMagick extension). One try with that.


What is the role of this extension?
I followed below some steps to connect magento2 with vue-storefront 
1. Cloned vue-storefront-api as per documentation and run with following commands 
2. Cloned Vue-storefront as per documentation and run with following commands 
3. Cloned Mage2vuefrontstore (mage2nosql) and run the following commands.
4. In local Magento admin panel system -> Integration -> done all steps in documentation

kindly let me know if anything missed

**Comment by Chiragsorathiya** [comment]
Hello team i have same product i cant see product image

**Comment by davevh** [comment]
I have the same problem here

**Comment by sprajapat770** [comment]
still this issue not solved.
