### ISSUE TITLE
error regionId..

### ISSUE THREAD

**Issue by marcelowu** [DivanteLtd/mage2vuestorefront#33]
npm run o2m

debug: Response received.
error: API call failed: Please check the shipping address information. "regionId
" is required. Enter and try again.
2018-09-02T02:16:02.990Z - error: Error placing an order Please check the shippi
ng address information. "regionId" is required. Enter and try again. string

**Comment by pkarw** [comment]
It seems like the region is is required by your Magento instance and hasn’t been provided by the user. You can set regionid as not required in Magento panel - stores - configuration.

You can also modify the checkout in VS to make this field required
