### ISSUE TITLE
Indexer not working properly

### ISSUE THREAD

**Issue by Darwex** [DivanteLtd/mage2vuestorefront#40]
Hi.

I have some issues with indexing Magento 2 instance to elastic search. I have tried several methods to index the data, the one mentioned below was the most successful one. However, some products are assigned in wrong categories or missing.

```
node --harmony cli.js categories --removeNonExistent=true
node --harmony cli.js productcategories --partitions=1
node --harmony cli.js attributes --removeNonExistent=true
node --harmony cli.js taxrule --removeNonExistent=true
node --harmony cli.js products --removeNonExistent=true --partitions=1
node --harmony cli.js reviews
````
and then

````
cd vue-storefront-api
npm run db rebuild -- --indexName=vue_storefront_catalog
````

Is there something I am not doing right?
Thanks.

**Comment by pkarw** [comment]
It seems like a proper sequence of commands; the category ids are stored in product.category_ids; please check some examples manually and try to debug the issue - it's hard to say what's happening in this particular case but nobody else was expiriencing this problem yet

**Comment by Darwex** [comment]
Thanks for your reply. I am not sure where to check that. Since there is only obscure generated IDs in IndexedDD, not sure where should I look for the data :-(

**Comment by Darwex** [comment]
Is there any place where I can see imported data in human  readable form?

**Comment by Darwex** [comment]
I used Kibana included in package to see imported data. All data was imported, issue seem to be caused by custom front-end modules which were modifying what was shown in template. 

Thanks :-)
