### ISSUE TITLE
erro redis with password

### ISSUE THREAD

**Issue by wubuyun** [DivanteLtd/mage2vuestorefront#42]
redis: {
    host: '127.0.0.1',
    port: 6379,
    password: 'HTKks8evmIF',
    db: 4
  },
is correct ?

**Comment by wubuyun** [comment]
error: uncaughtException: Ready check failed: NOAUTH Authentication required. date=Sat Nov 10 2018 04:49:58 GMT+0000 (UTC), pid=27101, uid=0, gid=0, cwd=/var/www/html/api, execPath=/usr/bin/node, version=v8.12.0, argv=[/usr/bin/node, /var/www/html/api/node_modules/mage2vuestorefront/src/cli.js,

**Comment by Simonwep** [comment]
I have the same issue :(
See log below:

> error: uncaughtException: Ready check failed: NOAUTH Authentication required. date=Mon Mar 04 2019 20:48:36 GMT+0000 (Coor                                                                         dinated Universal Time), pid=29381, uid=0, gid=0, cwd=/home/vsf/vue-storefront-api, execPath=/usr/bin/node, version=v10.15                                                                         .0, argv=[/usr/bin/node, /home/vsf/vue-storefront-api/node_modules/mage2vuestorefront/src/cli.js, products, --removeNonExi                                                                         stent=true, --partitions=1], rss=69365760, heapTotal=43855872, heapUsed=24676160, external=75651, loadavg=[2.513671875, 1.                                                                         7724609375, 3.5654296875], uptime=6568351, trace=[column=12, file=/home/vsf/vue-storefront-api/node_modules/redis-parser/l                                                                         ib/parser.js, function=parseError, line=193, method=null, native=false, column=14, file=/home/vsf/vue-storefront-api/node_                                                                         modules/redis-parser/lib/parser.js, function=parseType, line=303, method=null, native=false], stack=[ReplyError: Ready che                                                                         ck failed: NOAUTH Authentication required.,     at parseError (/home/vsf/vue-storefront-api/node_modules/redis-parser/lib/                                                                         parser.js:193:12),     at parseType (/home/vsf/vue-storefront-api/node_modules/redis-parser/lib/parser.js:303:14)]
