### ISSUE TITLE
Wrong type if bool options are passed from commandline

### ISSUE THREAD

**Issue by revlis-x** [DivanteLtd/mage2vuestorefront#53]
E.g. `extendedCategories` import is not working as it should with the provided scripts since `--extendedCategories=true` is evaluated as a String.

Furthermore inside `src/cli.js` it defaults to `true` when not specified, where it should be opt-in.

**Comment by pkarw** [comment]
Can You please propose a pull request with a fix?

**Comment by revlis-x** [comment]
This is resolved by #54
