### ISSUE TITLE
Page & partitionSize options don't iterate pages

### ISSUE THREAD

**Issue by hunterjamesio** [DivanteLtd/mage2vuestorefront#59]
I haven't fully diagnosed this yet or looked at a solution but know that commit 155c1143a0e448999ea4394d102cf39d37180037 is where this is introduced.

When using these, the products indexer doesn't seem to actually move past the specified page - instead just continuously looping the same requests.

**Comment by pkarw** [comment]
Please try this fix https://github.com/DivanteLtd/mage2vuestorefront/commit/231196040412a4a7001d452a88c07a400a26592b

**Comment by hunterjamesio** [comment]
Perfect! Nice one, thanks so much.
