### ISSUE TITLE
Catalog Import Paging Issue

### ISSUE THREAD

**Issue by rain2o** [DivanteLtd/mage2vuestorefront#60]
I am running into an issue when trying to import the catalog from Magento 2. It appears to be on a never ending loop where it is trying to increment pages but stays on `currentPage=1`. 

I noticed commit 231196040412a4a7001d452a88c07a400a26592b which appeared to resolve the issue, but I have the updated source code locally and the issue still persists. 

After some further debugging I noticed that `context.page` is actually `null` at the point it is being checked in `adapters/abstract.js`. For local testing I changed the condition [here](https://github.com/DivanteLtd/mage2vuestorefront/blob/231196040412a4a7001d452a88c07a400a26592b/src/adapters/abstract.js#L193) to the following:

```
if (context.page) { 
  context.page++
  this.page++;
} else {
  context.page = ++this.page;
}
```
So far this appears to have resolved the issue. I don't know if there is another root cause somewhere deeper and if this is just a band-aid fix, but I wanted to report my findings.

**Comment by pkarw** [comment]
Thanks! It requires kind of refactoring; for sure :) this solution should be a valid one. There simply shouldn’t be this this.page/context.page separation. But for now it’s fine - could You please send it as a pull request?

**Comment by rain2o** [comment]
Thanks for the confirmation @pkarw! I’ll submit a PR tomorrow morning.

**Comment by pkarw** [comment]
Thanks! It was classical me: I’ve fixed one thing and broken another one haha :) thanks for Your help!

**Comment by pkarw** [comment]
Ok, I've already fixed it :) Thanks for the solution!
