### ISSUE TITLE
Use Magento CMS API instead of 3rd party

### ISSUE THREAD

**Issue by rain2o** [DivanteLtd/mage2vuestorefront#65]
Currently it looks like there is a 3rd party dependency on [snowdog/module-cms-api](https://github.com/SnowdogApps/magento2-cms-api) for retrieving CMS data currently. Magento has API endpoints for this purpose already. Is there a feature or ability that this 3rd party module provides that Magento does not? At first glance it seems this can be replaced by Magento's core API and remove this dependency.

**Comment by pkarw** [comment]
@anqaka can You say sth more on this?

**Comment by anqaka** [comment]
HI, Default Magento API didn't parse WYSIWYG to HTML, so we got data like from admin panel. This module parse the content of CMS block & pages to display it on frontend. Maybe in Magento 2.3 it's already fixed? I didn't tested.

**Comment by rain2o** [comment]
Ahh, ok @anqaka I missed that piece. Makes sense. Doesn't look like they have made any changes to that in 2.3
