### ISSUE TITLE
Limit of total fields [1000] in index [vue_storefront_catalog] has been exceeded

### ISSUE THREAD

**Issue by yohanespradono** [DivanteLtd/mage2vuestorefront#81]
Hi,

I got this error while running mage2vs import

Limit of total fields [1000] in index [vue_storefront_catalog] has been exceeded

How to increase the field setting on index after index creation?

**Comment by yohanespradono** [comment]
I added following code to my api/config/elasticsearch.schema.index.json

```
      "index" : {
        "mapping": {
          "total_fields": {
            "limit": 2000
          }
        }
      }
```

**Comment by pkarw** [comment]
Cool thanks for the hint
