### ISSUE TITLE
Custom attributes in child products of configurable product

### ISSUE THREAD

**Issue by Cheeerd** [DivanteLtd/mage2vuestorefront#93]
https://github.com/DivanteLtd/mage2vuestorefront/blob/c71788e1c918225685344657f9d6ca0b2417d801/src/adapters/magento/product.js#L421
There are commented "custom_attributes: prOption.custom_attributes" on line  421. Why is that so? I need custom attributes to be overridden from child when configuring a configurable product. So, if i uncomment this line, custom attributes begin being indexed in elastic and it starts work properly in vuestorefront.

**Comment by pkarw** [comment]
The custom attrbutes are already there - https://github.com/DivanteLtd/mage2vuestorefront/blob/c71788e1c918225685344657f9d6ca0b2417d801/src/adapters/magento/product.js#L424 - they're loaded and extrapolated as standard `confChild` properties (not the bundled into `custom_attributes`). VS is supportng bot formats by the way

**Comment by Cheeerd** [comment]
Yeah, indeed. I was confused by code like this https://github.com/DivanteLtd/vue-storefront/blob/ae793cbaaa8c992b517e7264f3737afcbb4b625f/core/modules/catalog/helpers/index.ts#L491, which appears in several places. And the attribute wasn't shown up at first time because of misconfiguration in magento ("use in product listing" property).
